{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOiZGarINBn70oDhvwBEkqE",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/MohammedHasan0898/BizcardX-Extracting-Business-Card-data-with-OCR/blob/main/BizcardX_Extracting_Business_Card_data_with_OCR.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile bizcardx.py\n",
        "import pandas as pd\n",
        "import streamlit as st\n",
        "import easyocr\n",
        "import mysql.connector\n",
        "from mysql.connector import (connection)\n",
        "from streamlit_option_menu import option_menu\n",
        "from PIL import Image\n",
        "import cv2\n",
        "import os\n",
        "import matplotlib.pyplot as plt\n",
        "import re\n",
        "\n",
        "\n",
        "\n",
        "icon = Image.open(\"C:/Users/admin/images/bizcard_icon.png\")\n",
        "\n",
        "\n",
        "# SETTING PAGE CONFIGURATIONS\n",
        "st.set_page_config(\n",
        "    page_title=\" Extracting Business Card Data with OCR \",\n",
        "    page_icon=icon,\n",
        "    layout=\"wide\",\n",
        "    initial_sidebar_state=\"expanded\")\n",
        "\n",
        "# Add custom CSS to adjust the layout\n",
        "st.markdown(\n",
        "    \"\"\"\n",
        "    <style>\n",
        "    .stApp {\n",
        "        display: flex;\n",
        "        flex-direction: column;\n",
        "        align-items: flex-start;\n",
        "    }\n",
        "    .stApp > div:first-child {\n",
        "        order: -1;\n",
        "    }\n",
        "    </style>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "# Create a container for the icon and title\n",
        "icon_url = \"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSv11x2suJu2zqPU8yxBof44oe-gfiE9wxDw&usqp=CAU\"\n",
        "title = \"Extracting Business Card Data with OCR\"\n",
        "st.markdown(\n",
        "    f'<div><img src=\"{icon_url}\" alt=\"Icon\" style=\"height: 50px; margin-right: 10px;\">{title}</div>',\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "\n",
        "#Title\n",
        "st.title(\"Extracting Business Card Data with OCR\")\n",
        "\n",
        "\n",
        "# SETTING-UP BACKGROUND IMAGE\n",
        "def setting_bg():\n",
        "    st.markdown(f\"\"\"<style>.stApp {{\n",
        "                        background:url(\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT84jxS3JUAxw4zAOe3_uZ6Zd2VAk8HzF0ZTg&usqp=CAU\");\n",
        "                        background-size: cover;\n",
        "                    }}\n",
        "                    </style>\"\"\", unsafe_allow_html=True)\n",
        "setting_bg()\n",
        "\n",
        "\n",
        "\n",
        "# OPTION MENUS\n",
        "with st.sidebar:\n",
        "    selected = option_menu(\"Menu\", [\"Home\",\"Upload and Extract and Store\",\"Modify\"],\n",
        "                          default_index=0,\n",
        "                          orientation=\"vertical\",\n",
        "                          styles={\"nav-link\": {\"font-size\": \"20px\", \"text-align\": \"centre\", \"margin\": \"0px\",\n",
        "                                                \"--hover-color\": \"#FF0000\"},\n",
        "                                   \"icon\": {\"font-size\": \"40px\"},\n",
        "                                   \"container\" : {\"max-width\": \"2000px\"},\n",
        "                                   \"nav-link-selected\": {\"background-color\": \"#D3D3D3\"},\n",
        "                                   \"nav\": {\"background-color\": \"#D3D3D3\"}})\n",
        "\n",
        "# INITIALIZING THE EasyOCR READER\n",
        "reader = easyocr.Reader(['en'])\n",
        "\n",
        "# CONNECTING WITH MYSQL DATABASE\n",
        "conn = connection.MySQLConnection(host=\"localhost\", user=\"root\", port='3306', database=\"YOUR DATABASE\", password=\"YOUR PASSWORD\")\n",
        "cur = conn.cursor()\n",
        "\n",
        "# TABLE CREATION\n",
        "cur.execute('''CREATE TABLE IF NOT EXISTS Business_Cards\n",
        "                   (id INTEGER PRIMARY KEY AUTO_INCREMENT,\n",
        "                    company_name VARCHAR(50),\n",
        "                    card_holder VARCHAR(50),\n",
        "                    designation VARCHAR(50),\n",
        "                    mobile_number VARCHAR(50),\n",
        "                    email TEXT,\n",
        "                    website TEXT,\n",
        "                    area TEXT,\n",
        "                    city VARCHAR(50),\n",
        "                    state VARCHAR(50),\n",
        "                    pin_code VARCHAR(10),\n",
        "                    image LONGBLOB\n",
        "                    )''')\n",
        "\n",
        "# HOME MENU\n",
        "if selected == \"Home\":\n",
        "     # Title Image\n",
        "    image = \"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-mnIkBDCJ8COUP5ihU51dyVCoDTC8YuTbug&usqp=CAU\"\n",
        "\n",
        "    # Display the icon image at the top\n",
        "    st.sidebar.image(image, use_column_width=True)\n",
        "\n",
        "\n",
        "    st.markdown(\":black_large_square: **Project Title** : BizCardX: Extracting Business Card Data with OCR\")\n",
        "\n",
        "    technologies = \"streamlit GUI, SQL, Data Extraction\"\n",
        "    st.markdown(f\":black_large_square: **Technologies** : {technologies}\")\n",
        "\n",
        "    overview = \"Streamlit application that allows users to upload an image of a business card and extract relevant information from it using easyOCR.\"\n",
        "    st.markdown(f\":black_large_square: **Overview** : {overview}\")\n",
        "    icon_url = \"https://png.pngitem.com/pimgs/s/30-304321_business-cards-png-business-card-mockup-png-transparent.png\"\n",
        "    st.image(icon_url,use_column_width=True)\n",
        "\n",
        "#Initialize df as None\n",
        "df= None\n",
        "\n",
        "# UPLOAD AND EXTRACT MENU\n",
        "if selected == \"Upload and Extract and Store\":\n",
        "     # Title Image\n",
        "    image = \"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-mnIkBDCJ8COUP5ihU51dyVCoDTC8YuTbug&usqp=CAU\"\n",
        "    # Display the icon image at the top\n",
        "    st.sidebar.image(image, use_column_width=True)\n",
        "\n",
        "\n",
        "    icon_url = \"https://png.pngitem.com/pimgs/s/30-304321_business-cards-png-business-card-mockup-png-transparent.png\"\n",
        "    st.image(icon_url,use_column_width=True)\n",
        "\n",
        "    tab1,tab2,tab3=st.tabs([\"UPLOAD\",\"EXTRACT\",\"STORE\"])\n",
        "    with tab1:\n",
        "        st.markdown(\"### Upload a Business Card\")\n",
        "        uploaded_card = st.file_uploader(\"Upload here\", label_visibility=\"collapsed\", type=[\"png\", \"jpeg\", \"jpg\"])\n",
        "\n",
        "        if uploaded_card is not None:\n",
        "            # Save the uploaded file to a temporary directory\n",
        "            temp_dir = os.path.join(\"uploaded_cards\")\n",
        "            os.makedirs(temp_dir, exist_ok=True)\n",
        "            temp_file_path = os.path.join(temp_dir, \"temp_card.jpg\")\n",
        "            with open(temp_file_path, \"wb\") as f:\n",
        "                f.write(uploaded_card.getbuffer())\n",
        "\n",
        "            # Display the uploaded card\n",
        "            st.markdown(\"### You have uploaded the card\")\n",
        "            st.image(uploaded_card)\n",
        "\n",
        "    with tab2:\n",
        "\n",
        "        if uploaded_card is not None:\n",
        "            if hasattr(uploaded_card, 'name') and uploaded_card.name is not None:\n",
        "                with open(os.path.join(\"uploaded_cards\", uploaded_card.name), \"wb\") as f:\n",
        "                    f.write(uploaded_card.getbuffer())\n",
        "                # Rest of the code that depends on uploaded_card\n",
        "                image = cv2.imread(temp_file_path)\n",
        "                res = reader.readtext(temp_file_path)\n",
        "                st.markdown(\"### Image Processed and Data Extracted\")\n",
        "\n",
        "\n",
        "                def image_preview(image, res):\n",
        "                    for (bbox, text, prob) in res:\n",
        "                       # unpack the bounding box\n",
        "                        (tl, tr, br, bl) = bbox\n",
        "                        tl = (int(tl[0]), int(tl[1]))\n",
        "                        tr = (int(tr[0]), int(tr[1]))\n",
        "                        br = (int(br[0]), int(br[1]))\n",
        "                        bl = (int(bl[0]), int(bl[1]))\n",
        "                        cv2.rectangle(image, tl, br, (0, 255, 0), 2)\n",
        "                        cv2.putText(image, text, (tl[0], tl[1] - 10),\n",
        "                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 0, 0), 2)\n",
        "                    plt.rcParams['figure.figsize'] = (15, 15)\n",
        "                    plt.axis('off')\n",
        "                    plt.imshow(image)\n",
        "\n",
        "                # DISPLAYING THE CARD WITH HIGHLIGHTS\n",
        "\n",
        "                with st.spinner(\"Please wait, processing image...\"):\n",
        "                        st.set_option('deprecation.showPyplotGlobalUse', False)\n",
        "                        saved_img = os.path.join(os.getcwd(), \"uploaded_cards\", uploaded_card.name)\n",
        "                        image = cv2.imread(saved_img)\n",
        "                        res = reader.readtext(saved_img)\n",
        "                        st.pyplot(image_preview(image, res))\n",
        "\n",
        "               # easyOCR\n",
        "                saved_img = os.path.join(os.getcwd(), \"uploaded_cards\", uploaded_card.name)\n",
        "                result = reader.readtext(saved_img, detail=0, paragraph=False)\n",
        "\n",
        "                # CONVERTING IMAGE TO BINARY TO UPLOAD TO SQL DATABASE\n",
        "                def img_to_binary(file):\n",
        "                    # Convert image data to binary format\n",
        "                    with open(file, 'rb') as file:\n",
        "                        binaryData = file.read()\n",
        "                    return binaryData\n",
        "\n",
        "                data = {\"company_name\": [],\n",
        "                        \"card_holder\": [],\n",
        "                        \"designation\": [],\n",
        "                        \"mobile_number\": [],\n",
        "                        \"email\": [],\n",
        "                        \"website\": [],\n",
        "                        \"area\": [],\n",
        "                        \"city\": [],\n",
        "                        \"state\": [],\n",
        "                        \"pin_code\": [],\n",
        "                        \"image\": img_to_binary(saved_img)\n",
        "                        }\n",
        "\n",
        "                def get_data(res):\n",
        "                     for ind, i in enumerate(res):\n",
        "                        # To get WEBSITE_URL\n",
        "                        if \"www \" in i.lower() or \"www.\" in i.lower():\n",
        "                               data[\"website\"].append(i)\n",
        "                        elif \"WWW\" in i:\n",
        "                               data[\"website\"] = res[4] + \".\" + res[5]\n",
        "                        # To get EMAIL ID\n",
        "                        elif \"@\" in i:\n",
        "                               data[\"email\"].append(i)\n",
        "                        # To get MOBILE NUMBER\n",
        "                        elif \"-\" in i:\n",
        "                             data[\"mobile_number\"].append(i)\n",
        "                        if len(data[\"mobile_number\"]) == 2:\n",
        "                             data[\"mobile_number\"] = \" & \".join(data[\"mobile_number\"])\n",
        "                        # To get COMPANY NAME\n",
        "                        elif ind == len(res) - 1:\n",
        "                            data[\"company_name\"].append(i)\n",
        "                        # To get CARD HOLDER NAME\n",
        "                        elif ind == 0:\n",
        "                            data[\"card_holder\"].append(i)\n",
        "                        # To get DESIGNATION\n",
        "                        elif ind == 1:\n",
        "                            data[\"designation\"].append(i)\n",
        "                        # To get AREA\n",
        "                        if re.findall('^[0-9].+, [a-zA-Z]+', i):\n",
        "                            data[\"area\"].append(i.split(',')[0])\n",
        "                        elif re.findall('[0-9] [a-zA-Z]+', i):\n",
        "                            data[\"area\"].append(i)\n",
        "                        # To get CITY NAME\n",
        "                        match1 = re.findall('.+St , ([a-zA-Z]+).+', i)\n",
        "                        match2 = re.findall('.+St,, ([a-zA-Z]+).+', i)\n",
        "                        match3 = re.findall('^[E].*', i)\n",
        "                        if match1:\n",
        "                            data[\"city\"].append(match1[0])\n",
        "                        elif match2:\n",
        "                            data[\"city\"].append(match2[0])\n",
        "                        elif match3:\n",
        "                            data[\"city\"].append(match3[0])\n",
        "                        # To get STATE\n",
        "                        state_match = re.findall('[a-zA-Z]{9} +[0-9]', i)\n",
        "                        if state_match:\n",
        "                            data[\"state\"].append(i[:9])\n",
        "                        elif re.findall('^[0-9].+, ([a-zA-Z]+);', i):\n",
        "                            data[\"state\"].append(i.split()[-1])\n",
        "                        if len(data[\"state\"]) == 2:\n",
        "                            data[\"state\"].pop(0)\n",
        "                        # To get PINCODE\n",
        "                        if len(i) >= 6 and i.isdigit():\n",
        "                            data[\"pin_code\"].append(i)\n",
        "                        elif re.findall('[a-zA-Z]{9} +[0-9]', i):\n",
        "                            data[\"pin_code\"].append(i[10:])\n",
        "                get_data(result)\n",
        "\n",
        "               # FUNCTION TO CREATE DATAFRAME\n",
        "                def create_df(data):\n",
        "                    df = pd.DataFrame(data)\n",
        "                    return df\n",
        "                df = create_df(data)\n",
        "                st.success(\"### Data Extracted!\")\n",
        "                st.write(df)\n",
        "                pass\n",
        "# STORING datas in mysql\n",
        "    with tab3:\n",
        "\n",
        "        if df is not None and not df.empty:\n",
        "            try:\n",
        "                # CONNECTING WITH MYSQL DATABASE\n",
        "                conn = connection.MySQLConnection(host=\"localhost\", user=\"root\", port='3306', database=\"om\", password=\"April123$\")\n",
        "                cur = conn.cursor()\n",
        "                for i, row in df.iterrows():\n",
        "                    sql = \"\"\"INSERT INTO Business_Cards(company_name,card_holder,designation,mobile_number,email,website,area,city,state,pin_code,image)\n",
        "                         VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)\"\"\"\n",
        "                    cur.execute(sql, tuple(row))\n",
        "                    # Commit the changes and close the cursor and connection\n",
        "                    conn.commit()\n",
        "                    cur.close()\n",
        "                    conn.close()\n",
        "                    st.success(\"Data uploaded to the database successfully!\")\n",
        "            except mysql.connector.Error as error:\n",
        "                st.error(f\"Failed to store data in the database: {error}\")\n",
        "        else:\n",
        "            st.warning(\"No data to store. Please upload and extract business card data first.\")\n",
        "            st.warning(\"No data to store. Please upload and extract business card data first.\")\n",
        "            pass\n",
        "\n",
        "# MODIFY MENU\n",
        "if selected == \"Modify\":\n",
        "     # Title Image\n",
        "    image = \"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-mnIkBDCJ8COUP5ihU51dyVCoDTC8YuTbug&usqp=CAU\"\n",
        "    # Display the icon image at the top\n",
        "    st.sidebar.image(image, use_column_width=True)\n",
        "\n",
        "\n",
        "    icon_url = \"https://png.pngitem.com/pimgs/s/30-304321_business-cards-png-business-card-mockup-png-transparent.png\"\n",
        "    st.image(icon_url,use_column_width=True)\n",
        "\n",
        "    col1, col2, col3 = st.columns([3, 3, 2])\n",
        "    col2.markdown(\"## Alteration and Deletion of Datas\")\n",
        "    column1, column2 = st.columns(2, gap=\"large\")\n",
        "\n",
        "    try:\n",
        "        with column1:\n",
        "            cur.execute(\"SELECT card_holder FROM Business_Cards\")\n",
        "            result = cur.fetchall()\n",
        "            business_cards = {row[0]: row[0] for row in result}\n",
        "\n",
        "            selected_card = st.selectbox(\"Select a card holder name to update\", list(business_cards.keys()))\n",
        "            st.markdown(\"#### Modify the Datas\")\n",
        "\n",
        "            cur.execute(\"SELECT company_name, card_holder, designation, mobile_number, email, website, area, city, state, pin_code FROM Business_Cards WHERE card_holder=%s\", (selected_card,))\n",
        "            result = cur.fetchone()\n",
        "\n",
        "            # DISPLAYING ALL THE INFORMATION\n",
        "            company_name = st.text_input(\"Company Name\", result[0])\n",
        "            card_holder = st.text_input(\"Card Holder\", result[1])\n",
        "            designation = st.text_input(\"Designation\", result[2])\n",
        "            mobile_number = st.text_input(\"Mobile Number\", result[3])\n",
        "            email = st.text_input(\"Email\", result[4])\n",
        "            website = st.text_input(\"Website\", result[5])\n",
        "            area = st.text_input(\"Area\", result[6])\n",
        "            city = st.text_input(\"City\", result[7])\n",
        "            state = st.text_input(\"State\", result[8])\n",
        "            pin_code = st.text_input(\"Pin Code\", result[9])\n",
        "\n",
        "            if st.button(\"Commit changes to DB\"):\n",
        "                # Update the information for the selected business card in the database\n",
        "                cur.execute(\"\"\"\n",
        "                    UPDATE Business_Cards\n",
        "                    SET company_name=%s, card_holder=%s, designation=%s, mobile_number=%s, email=%s, website=%s, area=%s, city=%s, state=%s, pin_code=%s\n",
        "                    WHERE card_holder=%s\n",
        "                \"\"\", (company_name, card_holder, designation, mobile_number, email, website, area, city, state, pin_code, selected_card))\n",
        "                conn.commit()\n",
        "                st.success(\"New Information updated in the database successfully.\")\n",
        "\n",
        "        with column2:\n",
        "            cur.execute(\"SELECT card_holder FROM Business_Cards\")\n",
        "            result =cur.fetchall()\n",
        "            business_cards = {row[0]: row[0] for row in result}\n",
        "\n",
        "            selected_card = st.selectbox(\"Select a card holder name to delete\", list(business_cards.keys()))\n",
        "            st.write(f\"### You have selected :green[**{selected_card}'s**] card to delete\")\n",
        "            st.write(\"#### Are You Sure\")\n",
        "\n",
        "            if st.button(\"Yes,sure\"):\n",
        "                cur.execute(f\"DELETE FROM Business_Cards WHERE card_holder='{selected_card}'\")\n",
        "                conn.commit()\n",
        "                st.success(\"Business card infos deleted from the database.\")\n",
        "    except:\n",
        "        st.warning(\" No data available in the database\")\n",
        "\n",
        "    if st.button(\"View updated data\"):\n",
        "        cur.execute(\"SELECT company_name, card_holder, designation, mobile_number, email, website, area, city, state, pin_code FROM Business_Cards\")\n",
        "        updated_data = pd.DataFrame(cur.fetchall(), columns=[\"Company Name\", \"Card Holder\", \"Designation\", \"Mobile Number\", \"Email\", \"Website\", \"Area\", \"City\", \"State\", \"Pin Code\"])\n",
        "        st.write(updated_data)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "aFVk44M-aYa4",
        "outputId": "5eb03475-f77a-4ac8-c02c-25960d03946b"
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting bizcardx.py\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install streamlit\n",
        "!pip install mysql.connector\n",
        "!pip install streamlit_option_menu"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "9qW1VO15bntY",
        "outputId": "0962ae33-6fa3-48ed-f453-edbaccd7deda"
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: streamlit in /usr/local/lib/python3.10/dist-packages (1.28.0)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)\n",
            "Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)\n",
            "Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.3.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)\n",
            "Requirement already satisfied: importlib-metadata<7,>=1.4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.8.0)\n",
            "Requirement already satisfied: numpy<2,>=1.19.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.23.5)\n",
            "Requirement already satisfied: packaging<24,>=16.8 in /usr/local/lib/python3.10/dist-packages (from streamlit) (23.2)\n",
            "Requirement already satisfied: pandas<3,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.5.3)\n",
            "Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.4.0)\n",
            "Requirement already satisfied: protobuf<5,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)\n",
            "Requirement already satisfied: pyarrow>=6.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.0.0)\n",
            "Requirement already satisfied: python-dateutil<3,>=2.7.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.8.2)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.31.0)\n",
            "Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.6.0)\n",
            "Requirement already satisfied: tenacity<9,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.2.3)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.5.0)\n",
            "Requirement already satisfied: tzlocal<6,>=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.2)\n",
            "Requirement already satisfied: validators<1,>=0.2 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.22.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.1.40)\n",
            "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.8.1b0)\n",
            "Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.2)\n",
            "Requirement already satisfied: watchdog>=2.1.5 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.0.0)\n",
            "Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.2)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.19.1)\n",
            "Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.11)\n",
            "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<7,>=1.4->streamlit) (3.17.0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2023.3.post1)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3,>=2.7.3->streamlit) (1.16.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.3.1)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.4)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2023.7.22)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (2.16.1)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.1)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)\n",
            "Requirement already satisfied: mysql.connector in /usr/local/lib/python3.10/dist-packages (2.2.9)\n",
            "Requirement already satisfied: streamlit_option_menu in /usr/local/lib/python3.10/dist-packages (0.3.6)\n",
            "Requirement already satisfied: streamlit>=0.63 in /usr/local/lib/python3.10/dist-packages (from streamlit_option_menu) (1.28.0)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (4.2.2)\n",
            "Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit>=0.63->streamlit_option_menu) (1.4)\n",
            "Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (5.3.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (8.1.7)\n",
            "Requirement already satisfied: importlib-metadata<7,>=1.4 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (6.8.0)\n",
            "Requirement already satisfied: numpy<2,>=1.19.3 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (1.23.5)\n",
            "Requirement already satisfied: packaging<24,>=16.8 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (23.2)\n",
            "Requirement already satisfied: pandas<3,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (1.5.3)\n",
            "Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (9.4.0)\n",
            "Requirement already satisfied: protobuf<5,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (3.20.3)\n",
            "Requirement already satisfied: pyarrow>=6.0 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (9.0.0)\n",
            "Requirement already satisfied: python-dateutil<3,>=2.7.3 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (2.8.2)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (2.31.0)\n",
            "Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (13.6.0)\n",
            "Requirement already satisfied: tenacity<9,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (8.2.3)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (4.5.0)\n",
            "Requirement already satisfied: tzlocal<6,>=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (5.2)\n",
            "Requirement already satisfied: validators<1,>=0.2 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (0.22.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (3.1.40)\n",
            "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (0.8.1b0)\n",
            "Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (6.3.2)\n",
            "Requirement already satisfied: watchdog>=2.1.5 in /usr/local/lib/python3.10/dist-packages (from streamlit>=0.63->streamlit_option_menu) (3.0.0)\n",
            "Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.4)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (3.1.2)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (4.19.1)\n",
            "Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.12.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=0.63->streamlit_option_menu) (4.0.11)\n",
            "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<7,>=1.4->streamlit>=0.63->streamlit_option_menu) (3.17.0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit>=0.63->streamlit_option_menu) (2023.3.post1)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3,>=2.7.3->streamlit>=0.63->streamlit_option_menu) (1.16.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (3.3.1)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (3.4)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (2023.7.22)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit>=0.63->streamlit_option_menu) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit>=0.63->streamlit_option_menu) (2.16.1)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=0.63->streamlit_option_menu) (5.0.1)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (2.1.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (23.1.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (2023.7.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.30.2)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.10.6)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit>=0.63->streamlit_option_menu) (0.1.2)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%run bizcardx.py"
      ],
      "metadata": {
        "id": "76-WlAb9drdN"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}